#!/usr/bin/env python

import os, signal, subprocess, sys, time

BUILD_DIR = 'build'
COLOR_RESET = "\033[0m"
COLOR_BOLD = "\033[1m"
COLOR_PRIMARY = "\033[33m"
COLOR_SECONDARY = "\033[36m"
COLOR_ERROR = "\033[31m"
ERROR_CODE = -1
TAB_SIZE = 4
QEMU = 'qemu-system-x86_64'
QEMU_ARGS = [
    QEMU,
    '-drive', f'format=raw,file={BUILD_DIR}/solace.img', 
    '-nic', 'none',
]

class cmd:
    def __init__(self, fn, aliases, desc=''):
        self.fn = fn
        self.aliases = aliases
        self.desc = desc

is_quiet = False

def info(msg):
    if is_quiet:
        return
    print(f"{COLOR_BOLD}{COLOR_PRIMARY}solace: {COLOR_RESET}{COLOR_BOLD}{msg}{COLOR_RESET}")

def usage():
    print(f'{COLOR_SECONDARY}{COLOR_BOLD}{args[0]} {COLOR_RESET}{COLOR_SECONDARY}[OPTIONS] [COMMAND]{COLOR_RESET}')
    print('')
    print(f'{COLOR_SECONDARY}{COLOR_BOLD}Commands:{COLOR_RESET}')
    max_len = 0
    for cmd in cmds:
        s = ', '.join(cmd.aliases)
        if len(s) > max_len:
            max_len = len(s)
    max_len = int((max_len + TAB_SIZE) / TAB_SIZE) * TAB_SIZE
    for cmd in cmds:
        s = ', '.join(cmd.aliases)
        print(f'{'':<{TAB_SIZE}}', end='')
        print(f'{COLOR_PRIMARY}{COLOR_BOLD}{s:<{max_len}}{COLOR_RESET}' + cmd.desc)

def error(msg, returncode = ERROR_CODE):
    print(f"{COLOR_BOLD}solace: {COLOR_ERROR}{COLOR_BOLD}error:{COLOR_RESET}", msg, file=sys.stderr)
    sys.exit(returncode)

def cmd_build():
    info('building kernel...')
    proc = subprocess.run(['meson', 'compile', '-C', BUILD_DIR])
    if proc.returncode != 0:
        error('failed to build kernel')
    sys.exit(proc.returncode)

def cmd_run():
    info('running kernel...')
    proc = subprocess.run(['meson', 'compile', '-C', BUILD_DIR], stdout=subprocess.DEVNULL)
    if proc.returncode != 0:
        error('failed to build kernel')
        sys.exit(proc.returncode)
    proc = subprocess.run(QEMU_ARGS)
    sys.exit(proc.returncode)

def cmd_test():
    info('attaching to kernel...')
    proc = subprocess.run(['meson', 'compile', '-C', BUILD_DIR], stdout=subprocess.DEVNULL)
    if proc.returncode != 0:
        error('failed to build kernel')
        sys.exit(proc.returncode)
    qemu_proc = subprocess.Popen(QEMU_ARGS + ['-s', '-S'])
    gdb_proc = subprocess.Popen(['gdb', '-q', '-x', 'gdb/k.gdb'])
    while qemu_proc.poll() is None and gdb_proc.poll() is None:
        time.sleep(0.1)
    if qemu_proc.poll() is None:
        qemu_proc.terminate()
    else:
        gdb_proc.kill()
    # GDB messes up terminal with external signal so try and fix it
    subprocess.run(['reset'])
    sys.exit(0)

cmds = [
    cmd(cmd_build, ['build', 'b'], 'builds kernel'),
    cmd(cmd_run, ['run', 'r'], 'runs kernel in QEMU'),
    cmd(cmd_test, ['test', 't'], 'runs kernel in QEMU and attaches GDB')
]

if __name__ == '__main__':
    args = sys.argv

    if len(args) < 2:
        usage()
        sys.exit(0)

    cmd_name = None
    for arg in args[1:]:
        if arg[0] == '-':
            for c in arg[1:]:
                if c == 'q':
                    is_quiet = True
                else:
                    error('unknown flag \'' + arg[0] + '\'')
        elif cmd_name is None:
            cmd_name = arg
        else:
            usage()
            sys.exit(ERROR_CODE)

    cmd = None
    for _cmd in cmds:
        if cmd_name in _cmd.aliases:
            cmd = _cmd
            break

    if cmd == None:
        usage()
        sys.exit(ERROR_CODE)

    cmd.fn()